services:
  app:
    build:
      context: ../docker
      dockerfile: Dockerfile
    container_name: php-learning-app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../src:/var/www
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: php-learning-nginx
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - app-network

  db:
    container_name: php-learning-db
    image: mysql:8.0
    volumes:
      - ./storage/db:/var/lib/mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
        - app-network

# Network is used to connect the containers in the same network
# Bridge Network: The bridge driver creates a private internal network on the host. Containers connected to this network
#                 can communicate with each other, but they are isolated from external networks unless explicitly exposed.
# Service Communication: Services on the same bridge network can communicate using their service names as hostnames.
#                        For example, the nginx service can reach the php service using the hostname php.
# Isolation: Containers on a bridge network are isolated from the host's network and other bridge networks,
#            providing a layer of security and organization.
networks:
  app-network:
    driver: bridge